### PR TITLE
Add feature to stop and start AWS RDS clusters associated with the namespace

### PR DESCRIPTION
**Pull request by apapia**
https://github.com/govirtuo/kube-ns-suspender/issues/104: Add feature to stop and start RDS clusters associated with the namespace

### CODE REVIEW

**Comment by eze-kiel** [comment]
Hi @apapia!

Did you try this at home or in a prod-like env? Unfortunately I can't easily test this

**Comment by apapia** [comment]
@eze-kiel I've had it running in our dev and qa kubernetes clusters for a few months with a lot of usage and is working great.

**Comment by eze-kiel** [comment]
Well, LGTM! Thanks for your contribution!

**Review by eze-kiel — APPROVED** [review]

**Comment by eze-kiel** [comment]
Hi @apapia, it seems that there is an issue with the image building workflow :/ I'll investigate

**Pull request merged**
