### PR TITLE
Feature/support pausing keda autoscaling

### PR DESCRIPTION
**Pull request by apapia**
Proposed implementation for issue #88

### CODE REVIEW

**Comment by eze-kiel** [comment]
Hi @apapia, thanks for your code improvement proposal! I'll review it as soon as possible.
Please note that this week is a busy one, so it may take a few days :sweat_smile:

**Comment by apapia** [comment]
@eze-kiel curious if you've had a chance to look at this yet

**Comment by apapia** [comment]
@eze-kiel - let me know if you are good with this PR

**Comment by eze-kiel** [comment]
hi @apapia, I blocked a time slot to look at your PR this evening

**Review by eze-kiel — APPROVED** [review]
Looks good for me, thanks for the tests and everything

**Pull request merged**
